#!/bin/bash


BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

BRANCH_PATTERN="^refs/heads/(feature|hotfix|release)/TIC-[0-9]+_[a-z0-9._-]+$"

if [[ ! "$BRANCH_NAME" =~ $BRANCH_PATTERN ]]; then
    echo "Error: Branch name '$BRANCH_NAME' does not follow the required naming convention."
    echo "Branch names must start with 'feature/', 'bugfix/', or 'hotfix/'."
    exit 1
fi